=== vasama/vsm/package_info.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"$id": "https://vasama.org/package_info.schema.json",

	"$defs": {
		"package-type-pattern": {
			"pattern": "((header|object|static|shared)?-library)|application"
		},
		"requirement-config-pattern": {
			"pattern": "(header|source|test)-(library|application)"
		}
	},

	"type": "object",
	"properties": {
		"is_root": {
			"type": "boolean"
		},
		"package": {
			"type": "string"
		},
		"version": {
			"type": "string"
		},
		"authors": {
			"type": "string"
		},
		"license": {
			"type": "string"
		},
		"website": {
			"type": "string"
		},
		"package_type": {
			"type": "string",
			"$ref": "#/$defs/package-type-pattern"
		},
		"requirements": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"package": {
						"type": "string"
					},
					"version": {
						"type": "string"
					},
					"configs": {
						"type": ["string", "array"],
						"$ref": "#/$defs/requirement-config-pattern",

						"items": {
							"type": "string",
							"$ref": "#/$defs/requirement-config-pattern"
						}
					}
				}
			}
		}
	}
}

=== vasama/vsm/library/hash_table/package_info.json
{
	"package": "vsm.hash_table",
	"version": "0.1",
	"package_type": "static-library",
	"requirements": [
		{
			"package": "vsm.container_core",
			"version": "0.1"
		},
		{
			"package": "vsm.core",
			"version": "0.1"
		},
		{
			"package": "vsm.hash",
			"version": "0.1"
		},
		{
			"package": "vsm.testing.allocator",
			"version": "0.1",
			"visible": false,
			"test": true
		}
	]
}

=== vasama/vsm/library-experimental/shared_string/package_info.json
{
	"package": "vsm-shared_string",
	"version": "0.1",
	"package_type": "header-library",
	"requirements": [
		{
			"package": "vsm-allocator",
			"version": "0.1"
		},
		{
			"package": "vsm-core",
			"version": "0.1"
		},
		{
			"package": "vsm-container_core",
			"version": "0.1"
		},
		{
			"package": "vsm-vector",
			"version": "0.1"
		}
	]
}

=== vasama/vsm/library/vector/package_info.json
{
	"package": "vsm.vector",
	"version": "0.1",
	"package_type": "header-library",
	"requirements": [
		{
			"package": "vsm.algorithm",
			"version": "0.1"
		},
		{
			"package": "vsm.core",
			"version": "0.1"
		},
		{
			"package": "vsm.testing.allocator",
			"version": "0.1",
			"visible": false,
			"test": true
		},
		{
			"package": "vsm.testing.core",
			"version": "0.1",
			"visible": false,
			"test": true
		}
	]
}

=== vasama/vsm/library/cli/package_info.json
{
	"package": "vsm.cli",
	"version": "0.1",
	"package_type": "static-library",
	"requirements": [
		{
			"package": "vsm.core",
			"version": "0.1"
		},
		{
			"package": "vsm.function",
			"version": "0.1"
		},
		{
			"package": "vsm.hash_table",
			"version": "0.1"
		},
		{
			"package": "vsm.result",
			"version": "0.1"
		},
		{
			"package": "vsm.streams",
			"version": "0.1"
		},
		{
			"package": "vsm.tag_ptr",
			"version": "0.1"
		},
		{
			"package": "vsm.vector",
			"version": "0.1"
		}
	]
}

=== vasama/vsm/library-experimental/shared_vector/package_info.json
{
	"package": "vsm-shared_vector",
	"version": "0.1",
	"package_type": "header-library",
	"requirements": [
		{
			"package": "vsm-allocator",
			"version": "0.1"
		},
		{
			"package": "vsm-core",
			"version": "0.1"
		},
		{
			"package": "vsm-vector",
			"version": "0.1"
		},
		{
			"package": "vsm-testing-allocator",
			"version": "0.1",
			"visible": false,
			"test": true
		},
		{
			"package": "vsm-testing-core",
			"version": "0.1",
			"visible": false,
			"test": true
		}
	]
}
